contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #aspa channel"
    url: https://nfcore.slack.com/channels/aspa
    about: Discussion about the nf-core/aspa pipeline
